// Generated by Wrangler by running `wrangler types`

interface Env {
	ckv: KVNamespace;
	token: "cjmscjms";
	session: DurableObjectNamespace /* Session from Session */;
	room: DurableObjectNamespace /* Room from Room */;
	limiter: DurableObjectNamespace /* Limiter from Limiter */;
	user: DurableObjectNamespace /* User from User */;
	cjb: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
