name: Deploy Cloudflare Pages
on:
  push:
    branches: [ "master", "preview" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: 20
          cache: "npm"